version: '2'
services:
  dockergo:
    image: romualdo/dockergo
    stdin_open: true
    tty: true
    labels:
      traefik.frontend.rule: Host:${HOST_RULE}
      traefik.port: '8080'
      traefik.enable: 'true'
      traefik.frontend.redirect.entryPoint: https
      io.rancher.container.pull_image: always
