version: '2'
catalog:
  name: DockerGo
  version: 0.0.1
  description: |
    DockerGo
services:
  dockergo:
    scale: 2
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 10000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 10000
